### ISSUE TITLE
Support for EAP versions

### ISSUE THREAD

**Issue by quom** [movatechtoday/jsonnet_templating_language_support#10]
Hi,

Is there any reason why the plugin is not supported on EAP versions? I am running PyCharm 2023.2 EAP (Professional Edition) and the plugin will not run. I am happy to provide testing feedback if there are bugs.

Thanks

**Comment by movatechtoday** [comment]
Hello @quom 

Thank you for raising the issues. I will take into processing and will try to provide you an update as soon as possible. 

I will let you know. 
Meanwhile, could you specify the os that you use?

**Comment by quom** [comment]
Hi, 

I am using macOS Ventura

**Comment by movatechtoday** [comment]
Thank you!

**Comment by quom** [comment]
Hi - do you have any update on this? I am still seeing that the plugin requires IDE build 231.* or earlier and the EAP build is 232

**Comment by indegro** [comment]
Hello.
I have updated the plugin. Now, the latest version is supported. The plugin is available on Marketplace

**Comment by movatechtoday** [comment]
Also, the new version contains support for Docsonnet and a new version of Grafonnet library.
