### ISSUE TITLE
"Unresolved variable reference" when using other parameters for the parameter default value

### ISSUE THREAD

**Issue by l-ehlers** [movatechtoday/jsonnet_templating_language_support#13]
Jsonnet allows to reference other parameters when defining the default value of a function parameter, see the example below.

However, Jsonnet Pro does not recognize the references and therefore shows an "unresolved variable reference" error (see screenshot of example). As Jsonnet is able to render the code listed below, this error seems to be a bug in Jsonnet Pro.

#### Jsonnet
```
function(
  a=1,
  b=a+1,
  c=a+b+1,
)
  { a: a, b: b, c: c }
```

#### Output
```
{
    "a": 1,
    "b": 2,
    "c": 4
}
```

#### Screenshot of Jsonnet Pro
![image](https://github.com/movatechtoday/jsonnet_pro/assets/59659067/50dfc68e-16bc-4f60-a83d-69c5ec1242fc)

**Comment by movatechtoday** [comment]
Thank you for posting the issue. Taking into processing

**Comment by movatechtoday** [comment]
The issues has been fixed. Also, I have added completions for parameters
