### ISSUE TITLE
Render on open

### ISSUE THREAD

**Issue by Puddinghat** [movatechtoday/jsonnet_templating_language_support#14]
Hello,

it would be good if instead of "Try to change the file on the left-hand side" when opening a Jsonnet file the code would just render immediately in the sidebar.

**Comment by movatechtoday** [comment]
Hello @Puddinghat 
Thank you for feature request. Taking into processing

**Comment by movatechtoday** [comment]
Hello.

I have added 2 new options that affect rendering of jsonnet files.
![image](https://github.com/movatechtoday/jsonnet_pro/assets/106426579/8341c375-fd25-497a-98bb-82ba9b2bf23e)

You can enabled these flags in the `Settings -> Tools -> Jsonnet -> AutoPreview `section


At the moment options are disabled. In the next release I am going to enable it. Testing shows the features are stable. 

I would appreciate if you test it.
