### ISSUE TITLE
Keep "Docsonnet Support" experimental feature flag toggleable

### ISSUE THREAD

**Issue by Puddinghat** [movatechtoday/jsonnet_templating_language_support#15]
We are using an internal custom docsonnet implementation with additional optional parameters for the fields (such as "schema", which adds a json schema for objects/ arrays). 
Thus, we are greeted with a lot of linter errors from the Jsonnet Pro Plugin when we use the docsonnet feature, even though the code is renderable.

Since I don't expect our internal features to be compatible with the mainline docsonnet in the future, would it be possible to keep this feature disableable even when it is not experimental anymore?

**Comment by movatechtoday** [comment]
Hello @Puddinghat 

Thank you for sharing your experience. You have a custom docsonnet library version and turned off the docsonnet support, right? 

In the subsequent releases, I can turn it off (default state) and add a notification in the Editor(one-time suggestion) that it can be enabled (if there is docsonnet usage in the file). 

Is it ok?

**Comment by movatechtoday** [comment]
The initial idea of utilizing Docsonnet was the following:
1. Extract the documentation of a function/value/object and show it as a tooltip.
2. Extract type information for the docsonnet definition, use it in Type Engine, verify code/show code completion/check types of arguments.

While experimenting with the second point (extracting type information), I have found the following:
`The standard docsonnet library cannot correctly encode required/optional parameters and parameters with default values`. 
The two language features have identical representations in docsonnet. 

Examples are here https://github.com/movatechtoday/jsonnet-pro-examples/tree/main/docsonnet/src 

Example that shows that two language features have the same encoding for required parameters and parameters with default values. https://github.com/movatechtoday/jsonnet-pro-examples/blob/main/docsonnet/src/03-optional-parameters-encoding.jsonnet 

I solved the issue by adding a new field to the encoding : "optional". The idea is to embed required/optional parameter info into the final representation. 

The source code of patched docsonnet library is here https://github.com/movatechtoday/docsonnet/blob/master/doc-util/main.libsonnet. 

Example of how to use it https://github.com/movatechtoday/jsonnet-pro-examples/blob/main/docsonnet/src/02-problem-optional-parameters.jsonnet 

Could you check when you have time if it is your case?

**Comment by Puddinghat** [comment]
Having it "enableable" would definitely help us a lot. We work in a lot of repositories and have to disable it in every single one of them. 

We basically have one additional optional parameter in value.new() that adds the option to define a json-schema definition for an array/object (we generate json-schemas out of docsonnet, so this helps with defining the contents for people working with the configuration file). Jsonnet Pro obviously does not know of this parameter and the linting breaks.

I have checked out the example repository and can confirm that the examples work - using optional parameters also gets parsed relatively quickly and the tooltips work.
But it doesn't work in our codebase at all currently, sadly. I'm thinking probably because of either a) the above modifications to docsonnet we are using and/or b) because of the docsonnet being nested a lot of times inside TLA-function files that look like this:


```
local __ = import 'scripts/docsonnet/doc-util/main.libsonnet';

function(
  dependencies=(import 'components/dummy-dependencies.libsonnet')(
    componentName='_example'
  )
)
  {
    '#test':: __.val(
      |||
        Test
      |||,
      __.T.string,
      self.test,
    ),
    test: 'helloWorld',
  }
```


I just wonder if optional should be defaulted to 'true' if the default value is not null. -- There are basically three states if I can see it correctly - there is a static default parameter (an actual value, default value is set to not null), there is a dynamic default parameter (it's the same as a different parameter, see https://github.com/movatechtoday/jsonnet_pro/issues/13, i would not know what to set default parameter to in this case, if the parameter it is referring to is required, also not defined) or the default value is 'null' (which could mean it's actually null or that it's a required parameter). For the last two occurances, docsonnet indeed can not tell us (always) if the parameter is optional or not, so the flag absolutely makes sense.

**Comment by movatechtoday** [comment]
Hello.
I have disabled type extract out of Docsonnet definition. The feature is disabled by default and is available in the new release
