### ISSUE TITLE
Update to IntelliJ 2023.3

### ISSUE THREAD

**Issue by Jezza** [movatechtoday/jsonnet_templating_language_support#17]
Heyo,

It's that time of year, and a new intellij version has been rolled out.

Any ETA when this plugin will be updated to be compat with it?

PS, love the plugin <3

**Comment by movatechtoday** [comment]
Hello.
The update for version 2023.3 is in testing phase and I plan to release it  on Monday. It should be available for download till Wednesday (need to wait for checks on Marketplace). 

Thank you for using the plugin

**Comment by bcapitanu-asapp** [comment]
@movatechtoday Thank you so much for the plugin!  My one wish, especially from us, the paying customers, is to please try to keep up with the PyCharm updates.  Often times PyCharm releases an update and it takes a long time for this plugin to get updated to work with the newest PyCharm update, and that's not ideal.   Other plugins don't have this issue.  Thank you for your consideration!

**Comment by movatechtoday** [comment]
I am happy to announce that the plugin has passed all verifications and is available on the marketplace.
