### ISSUE TITLE
Any way to actually render to JSON?

### ISSUE THREAD

**Issue by mikehearn** [movatechtoday/jsonnet_templating_language_support#2]
It'd be nice if the plugin could actually run jsonnet and show the evaluated results.

**Comment by movatechtoday** [comment]
Hello @mikehearn 
Thank you for the suggested functionality. Could you provide answers to the following questions to better understand your case?
- What OS do you use?
- Do you use plain jsonnet or with jsonnetbundle or with Grafana Tanka? 

Best regards,
MovaTech Today.

**Comment by mikehearn** [comment]
I was experimenting with jsonnet, so just plain jsonnet with nothing Grafana related. I'm using macOS. The other plugin (language server based) has an evaluate feature but there's no keybinding and if anything goes wrong like a syntax error it just throws an IDE exception. It'd be useful to have a split view where the rendered json can be shown on the right, like when working with HTML.

**Comment by movatechtoday** [comment]
Thank you for the explanation. We will take it into the processing and will try to deliver the first version in the next release (next planned is 2022.1.6)

**Comment by movatechtoday** [comment]
Hello @mikehearn 

The new version of the plugin is available on the Marketplace -- 2022.1.6. 
There is a new feature -- AutoPreview functionality. You can configure a path to the Jsonnet tool, and when you change a Jsonnet file, the plugin will render it in the preview pane.

**Comment by mikehearn** [comment]
Nice! I'll check it out!

**Comment by mikehearn** [comment]
@movatechtoday Works well, thanks! There are a few minor bugs:

1. Changing the output mode between JSON/YAML doesn't cause a re-render.
2. If you open a jsonnet file and the interpreter isn't set in the prefs, you go in and click "auto detect" and then click OK, it doesn't detect that the setting was changed. You have to close and reopen the file.

Nothing major though.

**Comment by movatechtoday** [comment]
Hello @mikehearn 

The mentioned issues have been fixed. Also, a new version of the plugin is available in the plugins repository.  

The new version contains a lot of nice features:

-  The inspection that checks if an external variable is configured
-  Defining of external variables and auto-completion for configured external variables
-  Spell checkers for comments/identifiers/string literals and more

More info here -- [Release 2022.1.7](https://jsonnet.movatech.today/docs/release_notes/version_2022.1.7/ )

Meantime, I close this ticket. Fill free to open a new one, if you want to see a new feature in the plugin.
