### ISSUE TITLE
syntax highlight not working for jsonnet files in Goland 2022.2.4

### ISSUE THREAD

**Issue by gtcslance** [movatechtoday/jsonnet_templating_language_support#3]
syntax highlight not working for jsonnet files in Goland 2022.2.4, but works for libsonnet files

**Comment by movatechtoday** [comment]
Hello @gtcslance 
Could you provide more context here? Or paste screenshots with examples when highlighting doesn't work? libsonnet and jsonnet files are highlighted by the same component.

**Comment by movatechtoday** [comment]
Could you also answer the following questions:
- What OS do you use?
- Does the completion work in the files that are not highlighted?

**Comment by gtcslance** [comment]
I'm using macOS 13.0.1 with M1 Pro chip.
Completion does not work in files that are not highlighted.

**Comment by gtcslance** [comment]
<img width="1323" alt="Screenshot 2022-11-17 at 10 09 20 PM" src="https://user-images.githubusercontent.com/22618271/202633146-27a0230f-ba59-44e3-861c-d17705fb2716.png">

**Comment by gtcslance** [comment]
<img width="1723" alt="Screenshot 2022-11-17 at 10 10 45 PM" src="https://user-images.githubusercontent.com/22618271/202633306-06dee4a4-317d-4dc8-a210-bb0ee2b8c667.png">

**Comment by indegro** [comment]
Hello @gtcslance 
It looks like files with .jsonnet extension were occasionally associated with another file type (plain text). Could you review your file type settings and check if jsonnet file type is associated with *.jsonnet pattern?

**Comment by indegro** [comment]
More information about file types configuration you can find here https://www.jetbrains.com/help/go/creating-and-registering-file-types.html

**Comment by indegro** [comment]
I think this section will be helpful to you -- https://www.jetbrains.com/help/go/creating-and-registering-file-types.html#configure-associations-between-filename-patterns-and-file-types

**Comment by gtcslance** [comment]
@indegro Thanks. Indeed jsonnet file type is not associated with *.jsonnet pattern. The issue is solved now.
