### ISSUE TITLE
New "argument inspector" doesn't take variables into account.

### ISSUE THREAD

**Issue by Jezza** [movatechtoday/jsonnet_templating_language_support#5]
I'm assuming it has something to do with out the type is (or isn't propagated) through the return value of an import.

![2023-04-11_09-23](https://user-images.githubusercontent.com/4224088/231087077-192e3e16-8ab2-4aa2-b109-fbd400c455b1.png)

We can see that `test` is resolved correctly, but `func` isn't, even though it produces exactly the same result.

**Comment by movatechtoday** [comment]
Hello @Jezza 
Thank you for posting the example!

The mentioned behavior is fixed in the latest version 2023.1.1.  It was released yesterday and should be available for download today. Please, check it in the Marketplace. 

https://plugins.jetbrains.com/plugin/18975-jsonnet-pro/versions
