### ISSUE TITLE
"External Variables" feature should be able to use "ext-code" instead of only "ext-string"

### ISSUE THREAD

**Issue by Puddinghat** [movatechtoday/jsonnet_templating_language_support#7]
Hello,

in our Jsonnet-codebase we extensively use ext-code external variables. However as far as we can see right now, this is not supported in the features added in https://jsonnet.movatech.today/docs/release_notes/version_2022.1.7/ .

It would be nice if this was supported in the future.

**Comment by movatechtoday** [comment]
Hi @Puddinghat 

Hello @quom
There is a new version of the plugin available. https://jsonnet.movatech.today/docs/release_notes/version_2023.1.2/

The AutoPreview config page has been extended with 3 additional options. 

Now it is possible to configure Jsonnet value/Raw string value for External Variables and TLAs

**Comment by movatechtoday** [comment]
I would appreciate if you fill in the survey and share your experience using the Jsonnet Pro plugin. 

https://www.surveymonkey.com/r/32JTDKS
