### ISSUE TITLE
Does not recognise imported function

### ISSUE THREAD

**Issue by quom** [movatechtoday/jsonnet_templating_language_support#8]
If I have a file like `func.jsonnet` with contents:

```
function(params) {
    foo: 'bar',
}
```
and file `main.jsonnet`
```
local func = import 'func.jsonnet';

{
    baz: func({}),
}
```
then jsonnet pro does not recognise the `func({})` call as a function:
<img width="470" alt="image" src="https://github.com/movatechtoday/jsonnet_pro/assets/4928671/cbcd6de7-a744-490d-a386-8c63fda77ef2">

If I change the function to be within a document rather than at the top level, e.g.:
```
{
    fn: function(params) { foo: 'bar', },
}
```
and import this file then `func.fn({})` is resolved correctly.

**Comment by movatechtoday** [comment]
Hello @quom
There is a new version of the plugin available. https://jsonnet.movatech.today/docs/release_notes/version_2023.1.2/

The issue should be fixed. 

I would like to thank you for the provided use case. It allow improving the plugin core and its ecosystem.

**Comment by movatechtoday** [comment]
I would appreciate if you fill in the survey and share your experience using the Jsonnet Pro plugin.

https://www.surveymonkey.com/r/32JTDKS
