### ISSUE TITLE
Suggestion/Autocomplete for grafonnet not working

### ISSUE THREAD

**Issue by albertteoh** [movatechtoday/jsonnet_templating_language_support#9]
I'm following the instructions from this [README](https://github.com/grafana/grafonnet/blob/main/gen/grafonnet-v9.4.0/docs/README.md) and related [examples](https://github.com/grafana/grafonnet/blob/main/gen/grafonnet-v9.4.0/docs/README.md); however I cannot see the `dashboard` option in the dropdown. 

When I run jsonnet with: `jsonnet -J vendor main.libsonnet`

It successfully generates the dashboard json:

```json
{
   "time": {
      "from": "now-6h",
      "to": "now"
   },
   "timezone": "utc",
   "title": "My Dashboard"
}
```

Which tells me that it was able to successfully find the `dashboard` object.

Do you know why it's missing from the "suggestions" dropdown? I'm expecting to see everything from the [subpackages list](https://github.com/grafana/grafonnet/blob/main/gen/grafonnet-v9.4.0/docs/README.md#subpackages).

![Screenshot 2023-06-16 at 11 30 55 am](https://github.com/movatechtoday/jsonnet_pro/assets/26584478/d0e25709-e90a-4ec0-a154-9bc35e24fde5)

**Comment by movatechtoday** [comment]
Hello @albertteoh 

Thank you for posting the question!

Yes, I can explain what is going on here. 
The old library (grafonnet-lib) defines everything manually: every object, function, method, etc. The plugin can parse it and provides you with code completion variants.

The new one uses another approach. Under the hood, it dynamically generates all the definitions for helper functions/methods/objects/values. These definitions are dynamic(generated when you interpret the code)

Internally the new grafonnet library uses the crdsonnet library for dynamically rendering all helper functions. These functions are available only when you try to render the code (when you interpret it). 

I am now figuring out how to statically pre-generate all the helper functions for the new grafonnet library. The dynamic nature of the new library limits the code completion only to what is defined in the files.

I am working on a new feature enabling code completion for the new grafonnet library.  

If you what to be a beta tester of this feature, email me at support@movatech.today.  I will configure a channel for the snapshot version and give you early access to the new functionality.

**Comment by movatechtoday** [comment]
Hi @albertteoh Can we close the ticket? I merged changes into the latest version.

**Comment by albertteoh** [comment]
> Hi @albertteoh Can we close the ticket? I merged changes into the latest version.

Yup, we can close it, thanks.
